name: kreatif
description: Aplikasi Buku Digital Kreatif.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  page_flip: ^1.0.1

flutter:
  uses-material-design: true
  assets:
    - File/Gambar/Buku/A.png
    - File/Gambar/Buku/B.png
    - File/Gambar/Buku/C.png
